import { bibliography } from '../bibliography';
import type { SEOSection } from '../../../types';
import type { ProjectFeeCalculatorUI } from '../ui';
import { createProjectFeeContent } from './content';

type LocaleData = {
  title: string;
  description: string;
  slug: string;
  numberLocale: string;
  ui: Omit<ProjectFeeCalculatorUI, 'numberLocale'>;
  faq: { question: string; answer: string }[];
  howTo: { name: string; text: string }[];
  seo: SEOSection[];
};

const commonSeo = (copy: {
  title: string;
  intro: string;
  formulaTitle: string;
  formula: string;
  scenarioTitle: string;
  scenario: string;
  bullets: string[];
  tip: string;
}): SEOSection[] => [
  { type: 'title', text: copy.title, level: 2 },
  { type: 'paragraph', html: copy.intro },
  { type: 'card', title: copy.formulaTitle, html: `<p>${copy.formula}</p><p>${copy.intro}</p>` },
  { type: 'code', code: copy.formula },
  { type: 'title', text: copy.scenarioTitle, level: 2 },
  { type: 'paragraph', html: copy.scenario },
  { type: 'list', items: copy.bullets },
  { type: 'tip', html: copy.tip },
];

const data: Record<string, LocaleData> = {
  de: {
    title: 'Projektgebühr-zu-Stundensatz-Rechner',
    description: 'Berechne den effektiven Stundensatz eines Festpreises nach Überarbeitungen, Besprechungen und direkten Kosten.',
    slug: 'projektgebuehr-zu-stundensatz-rechner',
    numberLocale: 'de-DE',
    ui: {
      labelFee: 'Feste Projektgebühr', labelPlannedHours: 'Arbeitsstunden', labelRevisions: 'Überarbeitungsrunden', labelRevisionHours: 'Stunden pro Überarbeitung', labelMeetings: 'Besprechungen', labelMeetingHours: 'Stunden pro Besprechung', labelDirectCosts: 'Direkte Projektkosten', labelTargetRate: 'Dein Ziel-Stundensatz', labelDelay: 'Szenario für Zusatzstunden', labelEffectiveRate: 'Effektiver Stundensatz', labelAfterCosts: 'Gebühr nach direkten Kosten', labelTotalHours: 'Realistische Projektstunden', labelHiddenHours: 'Zusätzliche Stunden', labelBufferedRate: 'Satz nach Szenario', labelRecommendedFee: 'Gebühr für dein Ziel', labelFeeGap: 'Verhandlungsspielraum', labelPlanned: 'Geplante Arbeit', labelHidden: 'Zusatzarbeit', labelWorkloadLedger: 'Stundenübersicht', labelHandsOn: 'Praktische Arbeit', labelRevisionTime: 'Überarbeitungszeit', labelMeetingTime: 'Besprechungszeit', labelScenarioTotal: 'Mit Szenariopuffer', labelBuffer: 'Szenario', labelCurrency: 'Währung', labelProjectMath: 'Projektberechnung', titleInputs: 'Unsichtbare Arbeit sichtbar machen', titleHiddenWork: 'Zusätzliche Arbeit', titleResults: 'Dein Projekt in Stunden', statusBelow: 'Unter deinem Ziel um', statusAtOrAbove: 'Auf oder über deinem Ziel um', statusNoHours: 'Füge mindestens eine Projektstunde hinzu, um den Satz zu sehen.', noteBeforeTax: 'Vor Steuern. Verwendet nur deine Eingaben und läuft im Browser.', btnBuffer0: 'Kein Puffer', btnBuffer10: '+10 %', btnBuffer25: '+25 %', btnBuffer50: '+50 %',
    },
    faq: [
      { question: 'Was zeigt der effektive Stundensatz?', answer: 'Er zeigt, was nach direkten Kosten pro Stunde von einer festen Projektgebühr übrig bleibt. Arbeitszeit, Überarbeitungen und Besprechungen werden gemeinsam betrachtet.' },
      { question: 'Welche Stunden gehören in die Schätzung?', answer: 'Trage zuerst die praktische Arbeitszeit ein und ergänze realistische Überarbeitungsrunden und Besprechungen. So bleiben die oft vergessenen Stunden sichtbar.' },
      { question: 'Wie funktioniert der Puffer?', answer: 'Der gewählte Prozentsatz wird auf die gesamten Projektstunden aufgeschlagen. Das ist ein Vergleichsszenario für zusätzlichen Aufwand und keine Terminprognose.' },
      { question: 'Wie wird die empfohlene Gebühr berechnet?', answer: 'Direkte Kosten werden zu den gesamten Stunden multipliziert mit deinem Ziel-Stundensatz addiert. Das ist eine persönliche Verhandlungsuntergrenze.' },
    ],
    howTo: [
      { name: 'Projektgebühr eingeben', text: 'Trage den Festpreis vor Steuern und Zahlungsgebühren ein.' },
      { name: 'Verborgene Arbeit ergänzen', text: 'Gib Arbeitsstunden, Überarbeitungen, Besprechungen und deren Dauer ein.' },
      { name: 'Szenario wählen', text: 'Prüfe mit 10 %, 25 % oder 50 %, wie zusätzlicher Aufwand den Satz verändert.' },
      { name: 'Mit deinem Ziel vergleichen', text: 'Setze deinen Ziel-Stundensatz und nutze die empfohlene Gebühr für die Verhandlung.' },
    ],
    seo: commonSeo({ title: 'Unsichtbare Projektstunden sichtbar machen', intro: 'Ein Festpreis wirkt nur dann attraktiv, wenn die Schätzung das ganze Projekt enthält. Überarbeitungen, Gespräche und direkte Kosten können aus einem guten Angebot eine schlecht bezahlte Verpflichtung machen.', formulaTitle: 'Die projektspezifische Formel', formula: 'Effektiver Stundensatz = (Festpreis - direkte Kosten) / (Arbeitsstunden + Überarbeitungsstunden + Besprechungsstunden).', scenarioTitle: 'Szenario vor der Verhandlung prüfen', scenario: 'Der Puffer behauptet nicht, dass jedes Projekt exakt so viel länger dauert. Er zeigt, ob der Preis auch bei zusätzlicher Arbeit noch sinnvoll bleibt.', bullets: ['Plane Kommunikation und Review-Zeit mit ein.', 'Halte direkte Kosten getrennt und sichtbar.', 'Nutze deinen eigenen Zielwert als Verhandlungsgrundlage.'], tip: 'Wenn der Satz mit Puffer unangenehm wird, erhöhe den Preis, begrenze den Umfang oder vereinbare ein Stundenlimit für Überarbeitungen.' }),
  },
  es: {
    title: 'Calculadora de tarifa efectiva de proyecto', description: 'Convierte un precio cerrado en una tarifa por hora real después de revisiones, reuniones y costes directos.', slug: 'calculadora-tarifa-efectiva-proyecto', numberLocale: 'es-ES',
    ui: { labelFee: 'Precio fijo del proyecto', labelPlannedHours: 'Horas de trabajo', labelRevisions: 'Rondas de revisión', labelRevisionHours: 'Horas por revisión', labelMeetings: 'Reuniones', labelMeetingHours: 'Horas por reunión', labelDirectCosts: 'Costes directos del proyecto', labelTargetRate: 'Tu tarifa objetivo por hora', labelDelay: 'Escenario de horas extra', labelEffectiveRate: 'Tarifa efectiva por hora', labelAfterCosts: 'Precio tras costes directos', labelTotalHours: 'Horas realistas del proyecto', labelHiddenHours: 'Horas adicionales', labelBufferedRate: 'Tarifa con escenario', labelRecommendedFee: 'Precio para alcanzar tu objetivo', labelFeeGap: 'Diferencia para negociar', labelPlanned: 'Trabajo previsto', labelHidden: 'Trabajo adicional', labelWorkloadLedger: 'Desglose de horas', labelHandsOn: 'Trabajo práctico', labelRevisionTime: 'Tiempo de revisión', labelMeetingTime: 'Tiempo de reuniones', labelScenarioTotal: 'Con margen de escenario', labelBuffer: 'Escenario', labelCurrency: 'Moneda', labelProjectMath: 'Cálculo del proyecto', titleInputs: 'Haz visible el trabajo oculto', titleHiddenWork: 'Trabajo adicional', titleResults: 'Tu proyecto, en horas', statusBelow: 'Por debajo de tu objetivo en', statusAtOrAbove: 'En o por encima de tu objetivo en', statusNoHours: 'Añade al menos una hora de proyecto para ver la tarifa.', noteBeforeTax: 'Antes de impuestos. Solo usa tus datos y funciona en el navegador.', btnBuffer0: 'Sin margen', btnBuffer10: '+10 %', btnBuffer25: '+25 %', btnBuffer50: '+50 %' },
    faq: [{ question: '¿Qué muestra la tarifa efectiva por hora?', answer: 'Muestra cuánto queda de un precio cerrado por cada hora después de restar los costes directos y sumar el trabajo práctico, las revisiones y las reuniones.' }, { question: '¿Qué horas debo incluir?', answer: 'Empieza por las horas de producción y añade rondas de revisión y reuniones realistas. Así las horas que suelen olvidarse quedan visibles.' }, { question: '¿Cómo funciona el margen?', answer: 'El porcentaje elegido se suma al total de horas del proyecto. Es un escenario para comparar presión o retrabajo adicional, no una predicción de fechas.' }, { question: '¿Cómo se calcula el precio recomendado?', answer: 'Suma los costes directos al total de horas multiplicado por tu tarifa objetivo. Es un suelo de negociación personal para ese proyecto.' }],
    howTo: [{ name: 'Introduce el precio fijo', text: 'Añade el importe que pagaría el cliente antes de impuestos y comisiones.' }, { name: 'Expón el trabajo oculto', text: 'Introduce horas de trabajo, revisiones, reuniones y la duración de cada una.' }, { name: 'Elige un escenario', text: 'Prueba 10 %, 25 % o 50 % para ver cómo cambia la tarifa si crece el trabajo.' }, { name: 'Compáralo con tu objetivo', text: 'Introduce tu tarifa deseada y usa el precio recomendado para aceptar o renegociar.' }],
    seo: commonSeo({ title: 'Haz que cuenten todas las horas del proyecto', intro: 'Un precio cerrado solo resulta atractivo si el cálculo incluye el proyecto completo. Las revisiones, las llamadas y los costes directos pueden convertir un presupuesto sano en un compromiso mal pagado.', formulaTitle: 'La fórmula de este proyecto', formula: 'Tarifa efectiva = (precio fijo - costes directos) / (horas de trabajo + horas de revisión + horas de reunión).', scenarioTitle: 'Usa el escenario antes de negociar', scenario: 'El margen no dice que todos los proyectos se retrasen exactamente ese porcentaje. Sirve para responder si el precio sigue teniendo sentido cuando aparece trabajo extra.', bullets: ['Presupuesta también comunicación y revisiones.', 'Mantén visibles los costes directos.', 'Usa tu propia tarifa objetivo como referencia.'], tip: 'Si la tarifa con margen no te convence, sube el precio, reduce el alcance o limita las revisiones y reuniones incluidas.' }),
  },
  fr: {
    title: 'Calculateur de tarif horaire de projet', description: 'Transformez un forfait en tarif horaire effectif après les révisions, les réunions et les coûts directs.', slug: 'calculateur-tarif-horaire-projet', numberLocale: 'fr-FR',
    ui: { labelFee: 'Forfait du projet', labelPlannedHours: 'Heures de travail', labelRevisions: 'Tours de révision', labelRevisionHours: 'Heures par révision', labelMeetings: 'Réunions', labelMeetingHours: 'Heures par réunion', labelDirectCosts: 'Coûts directs du projet', labelTargetRate: 'Votre tarif horaire cible', labelDelay: 'Scénario d’heures supplémentaires', labelEffectiveRate: 'Tarif horaire effectif', labelAfterCosts: 'Forfait après coûts directs', labelTotalHours: 'Heures réalistes du projet', labelHiddenHours: 'Heures supplémentaires', labelBufferedRate: 'Tarif avec scénario', labelRecommendedFee: 'Forfait pour atteindre la cible', labelFeeGap: 'Écart de négociation', labelPlanned: 'Travail prévu', labelHidden: 'Travail supplémentaire', labelWorkloadLedger: 'Répartition des heures', labelHandsOn: 'Travail pratique', labelRevisionTime: 'Temps de révision', labelMeetingTime: 'Temps de réunion', labelScenarioTotal: 'Avec marge de scénario', labelBuffer: 'Scénario', labelCurrency: 'Devise', labelProjectMath: 'Calcul du projet', titleInputs: 'Rendre le travail caché visible', titleHiddenWork: 'Travail supplémentaire', titleResults: 'Votre projet, en heures', statusBelow: 'En dessous de votre cible de', statusAtOrAbove: 'Au niveau ou au-dessus de votre cible de', statusNoHours: 'Ajoutez au moins une heure de projet pour voir le tarif.', noteBeforeTax: 'Avant impôts. Utilise uniquement vos données et fonctionne dans votre navigateur.', btnBuffer0: 'Sans marge', btnBuffer10: '+10 %', btnBuffer25: '+25 %', btnBuffer50: '+50 %' },
    faq: [{ question: 'Que montre le tarif horaire effectif ?', answer: 'Il indique ce qui reste d’un forfait par heure après déduction des coûts directs et addition du travail, des révisions et des réunions.' }, { question: 'Quelles heures faut-il inclure ?', answer: 'Commencez par les heures de production, puis ajoutez des révisions et réunions réalistes pour rendre visibles les heures souvent oubliées.' }, { question: 'Comment fonctionne la marge ?', answer: 'Le pourcentage choisi est ajouté au total des heures. Il s’agit d’un scénario de comparaison, pas d’une prévision de délai.' }, { question: 'Comment calculer le forfait conseillé ?', answer: 'Additionnez les coûts directs au total des heures multiplié par votre tarif cible. Cela fournit un seuil de négociation propre à ce projet.' }],
    howTo: [{ name: 'Saisir le forfait', text: 'Ajoutez le montant payé par le client avant impôts et frais de paiement.' }, { name: 'Ajouter le travail caché', text: 'Indiquez les heures pratiques, les révisions, les réunions et leur durée.' }, { name: 'Choisir un scénario', text: 'Testez 10 %, 25 % ou 50 % pour mesurer l’effet d’un travail supplémentaire.' }, { name: 'Comparer à votre cible', text: 'Saisissez le tarif souhaité et utilisez le forfait conseillé pour négocier.' }],
    seo: commonSeo({ title: 'Compter toutes les heures du projet', intro: 'Un forfait n’est intéressant que si l’estimation contient tout le projet. Révisions, appels et coûts directs peuvent transformer un devis correct en engagement sous-payé.', formulaTitle: 'La formule propre au projet', formula: 'Tarif effectif = (forfait - coûts directs) / (heures pratiques + heures de révision + heures de réunion).', scenarioTitle: 'Tester le scénario avant de négocier', scenario: 'La marge ne prétend pas que chaque projet dépassera exactement ce pourcentage. Elle permet de vérifier si le prix reste cohérent lorsque le travail augmente.', bullets: ['Incluez la communication et les retours.', 'Gardez les coûts directs visibles.', 'Fondez la négociation sur votre propre cible.'], tip: 'Si le tarif avec marge est trop bas, augmentez le forfait, réduisez le périmètre ou limitez les révisions incluses.' }),
  },
  it: {
    title: 'Calcolatore compenso progetto e tariffa oraria', description: 'Trasforma un compenso fisso nella tariffa oraria effettiva dopo revisioni, riunioni e costi diretti.', slug: 'calcolatore-compenso-progetto-tariffa-oraria', numberLocale: 'it-IT',
    ui: { labelFee: 'Compenso fisso del progetto', labelPlannedHours: 'Ore di lavoro', labelRevisions: 'Cicli di revisione', labelRevisionHours: 'Ore per revisione', labelMeetings: 'Riunioni', labelMeetingHours: 'Ore per riunione', labelDirectCosts: 'Costi diretti del progetto', labelTargetRate: 'La tua tariffa oraria obiettivo', labelDelay: 'Scenario di ore aggiuntive', labelEffectiveRate: 'Tariffa oraria effettiva', labelAfterCosts: 'Compenso dopo i costi diretti', labelTotalHours: 'Ore realistiche del progetto', labelHiddenHours: 'Ore aggiuntive', labelBufferedRate: 'Tariffa con scenario', labelRecommendedFee: 'Compenso per raggiungere l’obiettivo', labelFeeGap: 'Differenza da negoziare', labelPlanned: 'Lavoro previsto', labelHidden: 'Lavoro aggiuntivo', labelWorkloadLedger: 'Riepilogo delle ore', labelHandsOn: 'Lavoro pratico', labelRevisionTime: 'Tempo di revisione', labelMeetingTime: 'Tempo delle riunioni', labelScenarioTotal: 'Con margine scenario', labelBuffer: 'Scenario', labelCurrency: 'Valuta', labelProjectMath: 'Calcolo del progetto', titleInputs: 'Rendi visibile il lavoro nascosto', titleHiddenWork: 'Lavoro aggiuntivo', titleResults: 'Il tuo progetto, in ore', statusBelow: 'Sotto il tuo obiettivo di', statusAtOrAbove: 'Al livello o sopra il tuo obiettivo di', statusNoHours: 'Aggiungi almeno un’ora di progetto per vedere la tariffa.', noteBeforeTax: 'Prima delle imposte. Usa solo i dati inseriti e funziona nel browser.', btnBuffer0: 'Nessun margine', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: 'Cosa mostra la tariffa oraria effettiva?', answer: 'Mostra quanto resta di un compenso fisso per ogni ora dopo i costi diretti, includendo lavoro pratico, revisioni e riunioni.' }, { question: 'Quali ore devo includere?', answer: 'Inserisci prima le ore di produzione, poi cicli di revisione e riunioni realistici, così il lavoro spesso dimenticato resta visibile.' }, { question: 'Come funziona il margine?', answer: 'La percentuale scelta viene aggiunta alle ore totali del progetto. È uno scenario per confrontare lavoro extra, non una previsione delle scadenze.' }, { question: 'Come si calcola il compenso consigliato?', answer: 'Somma i costi diretti alle ore totali moltiplicate per la tua tariffa obiettivo. È una soglia personale per la trattativa.' }],
    howTo: [{ name: 'Inserisci il compenso fisso', text: 'Aggiungi l’importo pagato dal cliente prima di imposte e commissioni.' }, { name: 'Aggiungi il lavoro nascosto', text: 'Inserisci ore pratiche, revisioni, riunioni e durata di ciascuna.' }, { name: 'Scegli uno scenario', text: 'Prova 10%, 25% o 50% per vedere l’effetto di più lavoro sulla tariffa.' }, { name: 'Confronta con il tuo obiettivo', text: 'Inserisci la tariffa desiderata e usa il compenso consigliato per negoziare.' }],
    seo: commonSeo({ title: 'Conta ogni ora del progetto', intro: 'Un compenso fisso è interessante solo se la stima comprende l’intero progetto. Revisioni, chiamate e costi diretti possono trasformare un buon preventivo in un impegno sottopagato.', formulaTitle: 'La formula del progetto', formula: 'Tariffa effettiva = (compenso fisso - costi diretti) / (ore pratiche + ore di revisione + ore di riunione).', scenarioTitle: 'Prova lo scenario prima di negoziare', scenario: 'Il margine non sostiene che ogni progetto richieda esattamente quella percentuale in più. Serve a capire se il prezzo regge quando il lavoro cresce.', bullets: ['Includi comunicazione e feedback.', 'Tieni visibili i costi diretti.', 'Usa il tuo obiettivo come base della trattativa.'], tip: 'Se la tariffa con margine è troppo bassa, aumenta il compenso, riduci l’ambito o limita le revisioni incluse.' }),
  },
  pt: {
    title: 'Calculadora de valor do projeto para taxa horária', description: 'Transforme um valor fixo numa taxa horária efetiva depois de revisões, reuniões e custos diretos.', slug: 'calculadora-taxa-horaria-projeto', numberLocale: 'pt-PT',
    ui: { labelFee: 'Valor fixo do projeto', labelPlannedHours: 'Horas de trabalho', labelRevisions: 'Rondas de revisão', labelRevisionHours: 'Horas por revisão', labelMeetings: 'Reuniões', labelMeetingHours: 'Horas por reunião', labelDirectCosts: 'Custos diretos do projeto', labelTargetRate: 'A sua taxa horária objetivo', labelDelay: 'Cenário de horas extra', labelEffectiveRate: 'Taxa horária efetiva', labelAfterCosts: 'Valor após custos diretos', labelTotalHours: 'Horas realistas do projeto', labelHiddenHours: 'Horas adicionais', labelBufferedRate: 'Taxa com cenário', labelRecommendedFee: 'Valor para atingir o objetivo', labelFeeGap: 'Diferença para negociar', labelPlanned: 'Trabalho previsto', labelHidden: 'Trabalho adicional', labelWorkloadLedger: 'Resumo de horas', labelHandsOn: 'Trabalho prático', labelRevisionTime: 'Tempo de revisão', labelMeetingTime: 'Tempo de reuniões', labelScenarioTotal: 'Com margem de cenário', labelBuffer: 'Cenário', labelCurrency: 'Moeda', labelProjectMath: 'Cálculo do projeto', titleInputs: 'Tornar visível o trabalho oculto', titleHiddenWork: 'Trabalho adicional', titleResults: 'O seu projeto, em horas', statusBelow: 'Abaixo do seu objetivo por', statusAtOrAbove: 'No nível ou acima do seu objetivo por', statusNoHours: 'Adicione pelo menos uma hora de projeto para ver a taxa.', noteBeforeTax: 'Antes de impostos. Usa apenas os dados introduzidos e funciona no navegador.', btnBuffer0: 'Sem margem', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: 'O que mostra a taxa horária efetiva?', answer: 'Mostra quanto sobra de um valor fixo por hora depois dos custos diretos, incluindo trabalho prático, revisões e reuniões.' }, { question: 'Que horas devo incluir?', answer: 'Comece pelas horas de produção e acrescente revisões e reuniões realistas para revelar o tempo que costuma ficar esquecido.' }, { question: 'Como funciona a margem?', answer: 'A percentagem escolhida é adicionada ao total de horas. É um cenário para comparar trabalho extra, não uma previsão de prazos.' }, { question: 'Como é calculado o valor recomendado?', answer: 'Some os custos diretos ao total de horas multiplicado pela sua taxa objetivo. É um limite pessoal para negociar.' }],
    howTo: [{ name: 'Introduza o valor fixo', text: 'Adicione o montante pago pelo cliente antes de impostos e comissões.' }, { name: 'Revele o trabalho oculto', text: 'Indique horas práticas, revisões, reuniões e a duração de cada uma.' }, { name: 'Escolha um cenário', text: 'Teste 10%, 25% ou 50% para medir o efeito de mais trabalho na taxa.' }, { name: 'Compare com o seu objetivo', text: 'Introduza a taxa desejada e use o valor recomendado na negociação.' }],
    seo: commonSeo({ title: 'Faça todas as horas do projeto contar', intro: 'Um valor fixo só é atrativo quando a estimativa inclui o projeto inteiro. Revisões, chamadas e custos diretos podem transformar uma proposta saudável num compromisso mal pago.', formulaTitle: 'A fórmula específica do projeto', formula: 'Taxa efetiva = (valor fixo - custos diretos) / (horas práticas + horas de revisão + horas de reunião).', scenarioTitle: 'Teste o cenário antes de negociar', scenario: 'A margem não afirma que todos os projetos vão ultrapassar exatamente aquela percentagem. Mostra se o valor continua a fazer sentido quando o trabalho aumenta.', bullets: ['Inclua comunicação e feedback.', 'Mantenha os custos diretos visíveis.', 'Use a sua taxa objetivo como referência.'], tip: 'Se a taxa com margem for baixa, aumente o valor, reduza o âmbito ou limite as revisões incluídas.' }),
  },
  nl: {
    title: 'Calculator projectprijs naar uurtarief', description: 'Zet een vaste projectprijs om in een effectief uurtarief na revisies, vergaderingen en directe kosten.', slug: 'projectprijs-naar-uurtarief-calculator', numberLocale: 'nl-NL',
    ui: { labelFee: 'Vaste projectprijs', labelPlannedHours: 'Werkuren', labelRevisions: 'Revisierondes', labelRevisionHours: 'Uren per revisie', labelMeetings: 'Vergaderingen', labelMeetingHours: 'Uren per vergadering', labelDirectCosts: 'Directe projectkosten', labelTargetRate: 'Jouw gewenste uurtarief', labelDelay: 'Scenario extra uren', labelEffectiveRate: 'Effectief uurtarief', labelAfterCosts: 'Prijs na directe kosten', labelTotalHours: 'Realistische projecturen', labelHiddenHours: 'Extra uren', labelBufferedRate: 'Tarief met scenario', labelRecommendedFee: 'Prijs voor jouw doel', labelFeeGap: 'Onderhandelingsverschil', labelPlanned: 'Gepland werk', labelHidden: 'Extra werk', labelWorkloadLedger: 'Urenoverzicht', labelHandsOn: 'Praktisch werk', labelRevisionTime: 'Revisietijd', labelMeetingTime: 'Vergadertijd', labelScenarioTotal: 'Met scenariomarge', labelBuffer: 'Scenario', labelCurrency: 'Valuta', labelProjectMath: 'Projectberekening', titleInputs: 'Verborgen werk zichtbaar maken', titleHiddenWork: 'Extra werk', titleResults: 'Jouw project in uren', statusBelow: 'Onder jouw doel met', statusAtOrAbove: 'Op of boven jouw doel met', statusNoHours: 'Voeg minstens één projectuur toe om het tarief te zien.', noteBeforeTax: 'Voor belastingen. Gebruikt alleen jouw invoer en werkt in de browser.', btnBuffer0: 'Geen marge', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: 'Wat laat het effectieve uurtarief zien?', answer: 'Het laat zien wat er per uur overblijft van een vaste prijs na directe kosten, praktisch werk, revisies en vergaderingen.' }, { question: 'Welke uren moet ik opnemen?', answer: 'Begin met productieve werkuren en voeg realistische revisies en vergaderingen toe, zodat vergeten tijd zichtbaar blijft.' }, { question: 'Hoe werkt de marge?', answer: 'Het gekozen percentage wordt bij alle projecturen opgeteld. Het is een scenario voor extra werk en geen voorspelling van de planning.' }, { question: 'Hoe wordt de aanbevolen prijs berekend?', answer: 'Tel de directe kosten op bij de totale uren maal jouw gewenste uurtarief. Dat is een persoonlijke ondergrens voor de onderhandeling.' }],
    howTo: [{ name: 'Voer de vaste prijs in', text: 'Vul het bedrag in dat de klant betaalt voor belastingen en betaalfees.' }, { name: 'Maak extra werk zichtbaar', text: 'Voer werkuren, revisies, vergaderingen en hun duur in.' }, { name: 'Kies een scenario', text: 'Test 10%, 25% of 50% om het effect van extra werk te zien.' }, { name: 'Vergelijk met jouw doel', text: 'Vul jouw gewenste tarief in en gebruik de aanbevolen prijs bij de onderhandeling.' }],
    seo: commonSeo({ title: 'Laat elk projectuur meetellen', intro: 'Een vaste prijs is alleen aantrekkelijk als de schatting het hele project bevat. Revisies, gesprekken en directe kosten kunnen een gezonde offerte veranderen in een slecht betaald commitment.', formulaTitle: 'De projectspecifieke formule', formula: 'Effectief uurtarief = (vaste prijs - directe kosten) / (werkuren + revisie-uren + vergaderuren).', scenarioTitle: 'Gebruik het scenario voor je onderhandelt', scenario: 'De marge zegt niet dat ieder project precies dat percentage langer duurt. Ze laat zien of de prijs standhoudt wanneer het werk groeit.', bullets: ['Begroot communicatie en feedback.', 'Houd directe kosten zichtbaar.', 'Gebruik je eigen doel als onderhandelingsbasis.'], tip: 'Is het tarief met marge te laag, verhoog dan de prijs, verklein de scope of begrens de inbegrepen revisies.' }),
  },
  sv: {
    title: 'Kalkylator för projektavgift till timpris', description: 'Omvandla ett fast projektpris till ett effektivt timpris efter ändringar, möten och direkta kostnader.', slug: 'kalkylator-projektavgift-timpris', numberLocale: 'sv-SE',
    ui: { labelFee: 'Fast projektavgift', labelPlannedHours: 'Arbetstimmar', labelRevisions: 'Ändringsrundor', labelRevisionHours: 'Timmar per ändring', labelMeetings: 'Möten', labelMeetingHours: 'Timmar per möte', labelDirectCosts: 'Direkta projektkostnader', labelTargetRate: 'Ditt önskade timpris', labelDelay: 'Scenario för extra timmar', labelEffectiveRate: 'Effektivt timpris', labelAfterCosts: 'Avgift efter direkta kostnader', labelTotalHours: 'Realistiska projekttimmar', labelHiddenHours: 'Extra timmar', labelBufferedRate: 'Timpris med scenario', labelRecommendedFee: 'Avgift för att nå målet', labelFeeGap: 'Skillnad att förhandla', labelPlanned: 'Planerat arbete', labelHidden: 'Extra arbete', labelWorkloadLedger: 'Timöversikt', labelHandsOn: 'Praktiskt arbete', labelRevisionTime: 'Ändringstid', labelMeetingTime: 'Mötestid', labelScenarioTotal: 'Med scenariomarginal', labelBuffer: 'Scenario', labelCurrency: 'Valuta', labelProjectMath: 'Projektberäkning', titleInputs: 'Gör det dolda arbetet synligt', titleHiddenWork: 'Extra arbete', titleResults: 'Ditt projekt i timmar', statusBelow: 'Under ditt mål med', statusAtOrAbove: 'På eller över ditt mål med', statusNoHours: 'Lägg till minst en projekttimme för att se timpriset.', noteBeforeTax: 'Före skatt. Använder bara dina uppgifter och körs i webbläsaren.', btnBuffer0: 'Ingen marginal', btnBuffer10: '+10 %', btnBuffer25: '+25 %', btnBuffer50: '+50 %' },
    faq: [{ question: 'Vad visar det effektiva timpriset?', answer: 'Det visar vad som återstår per timme av en fast projektavgift efter direkta kostnader, praktiskt arbete, ändringar och möten.' }, { question: 'Vilka timmar ska jag ta med?', answer: 'Börja med produktionstimmarna och lägg till realistiska ändringar och möten så att bortglömd tid blir synlig.' }, { question: 'Hur fungerar marginalen?', answer: 'Den valda procentsatsen läggs till projektets totala timmar. Det är ett scenario för extra arbete, inte en tidsprognos.' }, { question: 'Hur räknas den rekommenderade avgiften ut?', answer: 'Lägg direkta kostnader till totala timmar multiplicerade med ditt målpris. Det blir en personlig förhandlingsgräns.' }],
    howTo: [{ name: 'Ange fast projektavgift', text: 'Skriv in beloppet kunden betalar före skatt och betalavgifter.' }, { name: 'Synliggör extra arbete', text: 'Ange arbetstimmar, ändringar, möten och deras längd.' }, { name: 'Välj ett scenario', text: 'Testa 10 %, 25 % eller 50 % för att se effekten av mer arbete.' }, { name: 'Jämför med ditt mål', text: 'Ange önskat timpris och använd den rekommenderade avgiften i förhandlingen.' }],
    seo: commonSeo({ title: 'Räkna med varje projekttimme', intro: 'Ett fast pris är bara attraktivt om uppskattningen innehåller hela projektet. Ändringar, samtal och direkta kostnader kan göra ett bra erbjudande till ett underbetalt åtagande.', formulaTitle: 'Projektets egen formel', formula: 'Effektivt timpris = (fast avgift - direkta kostnader) / (arbetstimmar + ändringstimmar + mötestimmar).', scenarioTitle: 'Testa scenariot innan du förhandlar', scenario: 'Marginalen säger inte att alla projekt tar exakt så mycket längre tid. Den visar om priset fortfarande håller när arbetet växer.', bullets: ['Planera in kommunikation och feedback.', 'Håll direkta kostnader synliga.', 'Använd ditt eget mål som grund.'], tip: 'Om timpriset med marginal känns för lågt, höj avgiften, minska omfattningen eller begränsa antalet ändringar.' }),
  },
  id: {
    title: 'Kalkulator biaya proyek ke tarif per jam', description: 'Ubah biaya proyek tetap menjadi tarif per jam efektif setelah revisi, rapat, dan biaya langsung.', slug: 'kalkulator-biaya-proyek-per-jam', numberLocale: 'id-ID',
    ui: { labelFee: 'Biaya tetap proyek', labelPlannedHours: 'Jam kerja langsung', labelRevisions: 'Putaran revisi', labelRevisionHours: 'Jam per revisi', labelMeetings: 'Rapat', labelMeetingHours: 'Jam per rapat', labelDirectCosts: 'Biaya langsung proyek', labelTargetRate: 'Target tarif per jam Anda', labelDelay: 'Skenario jam tambahan', labelEffectiveRate: 'Tarif per jam efektif', labelAfterCosts: 'Biaya setelah biaya langsung', labelTotalHours: 'Jam proyek realistis', labelHiddenHours: 'Jam tambahan', labelBufferedRate: 'Tarif setelah skenario', labelRecommendedFee: 'Biaya untuk mencapai target', labelFeeGap: 'Selisih untuk negosiasi', labelPlanned: 'Pekerjaan terencana', labelHidden: 'Pekerjaan tambahan', labelWorkloadLedger: 'Rincian jam kerja', labelHandsOn: 'Pekerjaan langsung', labelRevisionTime: 'Waktu revisi', labelMeetingTime: 'Waktu rapat', labelScenarioTotal: 'Dengan cadangan skenario', labelBuffer: 'Skenario', labelCurrency: 'Mata uang', labelProjectMath: 'Perhitungan proyek', titleInputs: 'Tampilkan pekerjaan tersembunyi', titleHiddenWork: 'Pekerjaan tambahan', titleResults: 'Proyek Anda dalam jam', statusBelow: 'Di bawah target Anda sebesar', statusAtOrAbove: 'Sama atau di atas target Anda sebesar', statusNoHours: 'Tambahkan setidaknya satu jam proyek untuk melihat tarif.', noteBeforeTax: 'Sebelum pajak. Hanya menggunakan input Anda dan berjalan di browser.', btnBuffer0: 'Tanpa cadangan', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: 'Apa yang ditunjukkan tarif per jam efektif?', answer: 'Tarif ini menunjukkan sisa biaya tetap per jam setelah biaya langsung dikurangi dan pekerjaan, revisi, serta rapat dihitung.' }, { question: 'Jam apa yang harus dimasukkan?', answer: 'Mulai dari jam produksi, lalu tambahkan revisi dan rapat yang realistis agar waktu yang sering terlupakan terlihat.' }, { question: 'Bagaimana cadangan bekerja?', answer: 'Persentase yang dipilih ditambahkan ke total jam proyek. Ini adalah skenario pekerjaan tambahan, bukan perkiraan tenggat.' }, { question: 'Bagaimana biaya rekomendasi dihitung?', answer: 'Biaya langsung ditambahkan ke total jam dikalikan target tarif Anda. Hasilnya adalah batas bawah pribadi untuk negosiasi.' }],
    howTo: [{ name: 'Masukkan biaya tetap', text: 'Tambahkan jumlah yang dibayar klien sebelum pajak dan biaya pembayaran.' }, { name: 'Tampilkan pekerjaan tambahan', text: 'Masukkan jam kerja, revisi, rapat, dan durasinya.' }, { name: 'Pilih skenario', text: 'Uji 10%, 25%, atau 50% untuk melihat dampak pekerjaan tambahan.' }, { name: 'Bandingkan dengan target', text: 'Masukkan tarif yang diinginkan dan gunakan biaya rekomendasi saat bernegosiasi.' }],
    seo: commonSeo({ title: 'Hitung setiap jam proyek', intro: 'Biaya tetap hanya terlihat menarik jika estimasinya mencakup seluruh proyek. Revisi, percakapan, dan biaya langsung dapat mengubah penawaran yang sehat menjadi pekerjaan yang kurang dibayar.', formulaTitle: 'Rumus khusus proyek', formula: 'Tarif efektif = (biaya tetap - biaya langsung) / (jam kerja + jam revisi + jam rapat).', scenarioTitle: 'Uji skenario sebelum bernegosiasi', scenario: 'Cadangan tidak menyatakan bahwa semua proyek akan bertambah persis sebesar persentase itu. Skenario ini menunjukkan apakah biaya tetap masih masuk akal saat pekerjaan bertambah.', bullets: ['Masukkan waktu komunikasi dan umpan balik.', 'Jaga biaya langsung tetap terlihat.', 'Gunakan target Anda sebagai dasar negosiasi.'], tip: 'Jika tarif dengan cadangan terlalu rendah, naikkan biaya, kurangi cakupan, atau batasi revisi yang termasuk.' }),
  },
  pl: {
    title: 'Kalkulator stawki godzinowej projektu', description: 'Zamień stałą cenę projektu na rzeczywistą stawkę godzinową po uwzględnieniu poprawek, spotkań i kosztów bezpośrednich.', slug: 'kalkulator-stawki-godzinowej-projektu', numberLocale: 'pl-PL',
    ui: { labelFee: 'Stała cena projektu', labelPlannedHours: 'Godziny pracy', labelRevisions: 'Rundy poprawek', labelRevisionHours: 'Godziny na poprawkę', labelMeetings: 'Spotkania', labelMeetingHours: 'Godziny na spotkanie', labelDirectCosts: 'Bezpośrednie koszty projektu', labelTargetRate: 'Docelowa stawka godzinowa', labelDelay: 'Scenariusz dodatkowych godzin', labelEffectiveRate: 'Rzeczywista stawka godzinowa', labelAfterCosts: 'Cena po kosztach bezpośrednich', labelTotalHours: 'Realistyczne godziny projektu', labelHiddenHours: 'Dodatkowe godziny', labelBufferedRate: 'Stawka ze scenariuszem', labelRecommendedFee: 'Cena dla osiągnięcia celu', labelFeeGap: 'Różnica do negocjacji', labelPlanned: 'Planowana praca', labelHidden: 'Dodatkowa praca', labelWorkloadLedger: 'Rozliczenie godzin', labelHandsOn: 'Praca wykonawcza', labelRevisionTime: 'Czas poprawek', labelMeetingTime: 'Czas spotkań', labelScenarioTotal: 'Z marginesem scenariusza', labelBuffer: 'Scenariusz', labelCurrency: 'Waluta', labelProjectMath: 'Kalkulacja projektu', titleInputs: 'Pokaż niewidoczną pracę', titleHiddenWork: 'Dodatkowa praca', titleResults: 'Twój projekt w godzinach', statusBelow: 'Poniżej celu o', statusAtOrAbove: 'Na poziomie lub powyżej celu o', statusNoHours: 'Dodaj co najmniej jedną godzinę projektu, aby zobaczyć stawkę.', noteBeforeTax: 'Przed podatkami. Korzysta tylko z podanych danych i działa w przeglądarce.', btnBuffer0: 'Bez marginesu', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: 'Co pokazuje rzeczywista stawka godzinowa?', answer: 'Pokazuje, ile z ceny stałej zostaje za godzinę po odjęciu kosztów bezpośrednich oraz dodaniu pracy, poprawek i spotkań.' }, { question: 'Jakie godziny uwzględnić?', answer: 'Zacznij od godzin wykonawczych, a następnie dodaj realistyczne poprawki i spotkania, aby ujawnić pomijany czas.' }, { question: 'Jak działa margines?', answer: 'Wybrany procent zostaje dodany do wszystkich godzin projektu. To scenariusz dodatkowej pracy, a nie prognoza terminu.' }, { question: 'Jak obliczana jest zalecana cena?', answer: 'Koszty bezpośrednie są dodawane do łącznej liczby godzin pomnożonej przez stawkę docelową. To osobista granica negocjacji.' }],
    howTo: [{ name: 'Wpisz stałą cenę', text: 'Dodaj kwotę płaconą przez klienta przed podatkami i opłatami.' }, { name: 'Ujawnij dodatkową pracę', text: 'Wpisz godziny pracy, poprawki, spotkania i ich czas.' }, { name: 'Wybierz scenariusz', text: 'Sprawdź 10%, 25% lub 50%, aby zobaczyć wpływ dodatkowej pracy.' }, { name: 'Porównaj z celem', text: 'Wpisz oczekiwaną stawkę i użyj zalecanej ceny podczas negocjacji.' }],
    seo: commonSeo({ title: 'Uwzględnij każdą godzinę projektu', intro: 'Stała cena jest atrakcyjna tylko wtedy, gdy wycena obejmuje cały projekt. Poprawki, rozmowy i koszty bezpośrednie mogą zmienić dobrą ofertę w niedochodowe zobowiązanie.', formulaTitle: 'Wzór dla tego projektu', formula: 'Rzeczywista stawka = (cena stała - koszty bezpośrednie) / (godziny pracy + godziny poprawek + godziny spotkań).', scenarioTitle: 'Sprawdź scenariusz przed negocjacją', scenario: 'Margines nie twierdzi, że każdy projekt potrwa dokładnie o ten procent dłużej. Pokazuje, czy cena nadal ma sens, gdy pracy przybywa.', bullets: ['Uwzględnij komunikację i opinie.', 'Trzymaj koszty bezpośrednie na widoku.', 'Oprzyj negocjacje na własnym celu.'], tip: 'Jeśli stawka z marginesem jest zbyt niska, podnieś cenę, ogranicz zakres lub ustal limit poprawek.' }),
  },
  tr: {
    title: 'Proje ücretinden saatlik ücret hesaplayıcı', description: 'Sabit proje ücretini revizyonlar, toplantılar ve doğrudan maliyetlerden sonra gerçek saatlik ücrete dönüştürün.', slug: 'proje-ucreti-saatlik-ucret-hesaplayici', numberLocale: 'tr-TR',
    ui: { labelFee: 'Sabit proje ücreti', labelPlannedHours: 'Çalışma saatleri', labelRevisions: 'Revizyon turları', labelRevisionHours: 'Revizyon başına saat', labelMeetings: 'Toplantılar', labelMeetingHours: 'Toplantı başına saat', labelDirectCosts: 'Doğrudan proje maliyetleri', labelTargetRate: 'Hedef saatlik ücretiniz', labelDelay: 'Ek saat senaryosu', labelEffectiveRate: 'Gerçek saatlik ücret', labelAfterCosts: 'Doğrudan maliyetlerden sonra ücret', labelTotalHours: 'Gerçekçi proje saatleri', labelHiddenHours: 'Ek saatler', labelBufferedRate: 'Senaryolu ücret', labelRecommendedFee: 'Hedefe ulaşmak için ücret', labelFeeGap: 'Pazarlık farkı', labelPlanned: 'Planlanan iş', labelHidden: 'Ek iş', labelWorkloadLedger: 'Saat dökümü', labelHandsOn: 'Uygulamalı iş', labelRevisionTime: 'Revizyon süresi', labelMeetingTime: 'Toplantı süresi', labelScenarioTotal: 'Senaryo payıyla', labelBuffer: 'Senaryo', labelCurrency: 'Para birimi', labelProjectMath: 'Proje hesabı', titleInputs: 'Gizli işi görünür kılın', titleHiddenWork: 'Ek iş', titleResults: 'Projeniz, saat olarak', statusBelow: 'Hedefinizin altında kalan fark', statusAtOrAbove: 'Hedefinizin üzerinde olan fark', statusNoHours: 'Ücreti görmek için en az bir proje saati ekleyin.', noteBeforeTax: 'Vergiler öncesi. Yalnızca girdiğiniz verileri kullanır ve tarayıcıda çalışır.', btnBuffer0: 'Pay yok', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: 'Gerçek saatlik ücret neyi gösterir?', answer: 'Doğrudan maliyetler düşüldükten ve iş, revizyon ve toplantı süreleri eklendikten sonra sabit ücretten saat başına ne kaldığını gösterir.' }, { question: 'Hangi saatleri eklemeliyim?', answer: 'Önce üretim saatlerini yazın, sonra unutulan zamanı görünür kılmak için gerçekçi revizyon ve toplantıları ekleyin.' }, { question: 'Pay nasıl çalışır?', answer: 'Seçilen yüzde toplam proje saatlerine eklenir. Bu, ek iş için bir senaryodur; teslim tarihi tahmini değildir.' }, { question: 'Önerilen ücret nasıl hesaplanır?', answer: 'Doğrudan maliyetler, toplam saatlerle hedef saatlik ücretin çarpımına eklenir. Bu proje için kişisel pazarlık tabanıdır.' }],
    howTo: [{ name: 'Sabit ücreti girin', text: 'Vergi ve ödeme komisyonlarından önce müşterinin ödeyeceği tutarı yazın.' }, { name: 'Ek işi görünür kılın', text: 'Çalışma saatlerini, revizyonları, toplantıları ve sürelerini ekleyin.' }, { name: 'Bir senaryo seçin', text: 'Ek işin ücreti nasıl değiştirdiğini görmek için %10, %25 veya %50 deneyin.' }, { name: 'Hedefinizle karşılaştırın', text: 'İstediğiniz ücreti girin ve pazarlıkta önerilen ücreti kullanın.' }],
    seo: commonSeo({ title: 'Projenin her saatini hesaba katın', intro: 'Sabit ücret ancak tahmin projenin tamamını içeriyorsa caziptir. Revizyonlar, görüşmeler ve doğrudan maliyetler iyi bir teklifi düşük ücretli bir taahhüde dönüştürebilir.', formulaTitle: 'Projeye özel formül', formula: 'Gerçek ücret = (sabit ücret - doğrudan maliyetler) / (çalışma saatleri + revizyon saatleri + toplantı saatleri).', scenarioTitle: 'Pazarlık öncesi senaryoyu deneyin', scenario: 'Pay, her projenin tam olarak bu yüzde kadar uzayacağını söylemez. İş büyüdüğünde fiyatın hâlâ mantıklı olup olmadığını gösterir.', bullets: ['İletişim ve geri bildirim süresini ekleyin.', 'Doğrudan maliyetleri görünür tutun.', 'Pazarlığı kendi hedefinize göre yapın.'], tip: 'Paylı ücret düşük kalıyorsa fiyatı artırın, kapsamı daraltın veya revizyon sınırı koyun.' }),
  },
  ru: {
    title: 'Калькулятор гонорара проекта в почасовую ставку', description: 'Переведите фиксированную стоимость проекта в эффективную почасовую ставку с учётом правок, встреч и прямых расходов.', slug: 'kalkulyator-stavki-proekta', numberLocale: 'ru-RU',
    ui: { labelFee: 'Фиксированная стоимость проекта', labelPlannedHours: 'Рабочие часы', labelRevisions: 'Раунды правок', labelRevisionHours: 'Часов на правку', labelMeetings: 'Встречи', labelMeetingHours: 'Часов на встречу', labelDirectCosts: 'Прямые расходы проекта', labelTargetRate: 'Ваша целевая ставка в час', labelDelay: 'Сценарий дополнительных часов', labelEffectiveRate: 'Эффективная ставка в час', labelAfterCosts: 'Стоимость после прямых расходов', labelTotalHours: 'Реалистичные часы проекта', labelHiddenHours: 'Дополнительные часы', labelBufferedRate: 'Ставка по сценарию', labelRecommendedFee: 'Стоимость для достижения цели', labelFeeGap: 'Разница для переговоров', labelPlanned: 'Планируемая работа', labelHidden: 'Дополнительная работа', labelWorkloadLedger: 'Разбор часов', labelHandsOn: 'Практическая работа', labelRevisionTime: 'Время на правки', labelMeetingTime: 'Время встреч', labelScenarioTotal: 'С учётом запаса', labelBuffer: 'Сценарий', labelCurrency: 'Валюта', labelProjectMath: 'Расчёт проекта', titleInputs: 'Сделайте скрытую работу видимой', titleHiddenWork: 'Дополнительная работа', titleResults: 'Ваш проект в часах', statusBelow: 'Ниже цели на', statusAtOrAbove: 'На уровне цели или выше на', statusNoHours: 'Добавьте хотя бы один час проекта, чтобы увидеть ставку.', noteBeforeTax: 'До налогов. Использует только введённые данные и работает в браузере.', btnBuffer0: 'Без запаса', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: 'Что показывает эффективная почасовая ставка?', answer: 'Она показывает, сколько остаётся от фиксированной стоимости за час после вычета прямых расходов и добавления работы, правок и встреч.' }, { question: 'Какие часы нужно учитывать?', answer: 'Начните с рабочих часов, затем добавьте реалистичные правки и встречи, чтобы учесть часто забываемое время.' }, { question: 'Как работает запас?', answer: 'Выбранный процент добавляется к общему числу часов проекта. Это сценарий дополнительной работы, а не прогноз сроков.' }, { question: 'Как рассчитывается рекомендуемая стоимость?', answer: 'Прямые расходы складываются с общими часами, умноженными на вашу целевую ставку. Это личная нижняя граница переговоров.' }],
    howTo: [{ name: 'Введите фиксированную стоимость', text: 'Укажите сумму, которую заплатит клиент до налогов и комиссий.' }, { name: 'Добавьте скрытую работу', text: 'Введите рабочие часы, правки, встречи и их длительность.' }, { name: 'Выберите сценарий', text: 'Проверьте 10%, 25% или 50%, чтобы увидеть влияние дополнительной работы.' }, { name: 'Сравните с целью', text: 'Введите желаемую ставку и используйте рекомендуемую стоимость в переговорах.' }],
    seo: commonSeo({ title: 'Учтите каждый час проекта', intro: 'Фиксированная цена привлекательна только тогда, когда оценка включает весь проект. Правки, разговоры и прямые расходы могут превратить хорошее предложение в низкооплачиваемое обязательство.', formulaTitle: 'Формула для конкретного проекта', formula: 'Эффективная ставка = (фиксированная стоимость - прямые расходы) / (рабочие часы + часы правок + часы встреч).', scenarioTitle: 'Проверьте сценарий до переговоров', scenario: 'Запас не утверждает, что каждый проект займёт ровно на этот процент больше времени. Он показывает, сохраняет ли цена смысл при росте объёма работы.', bullets: ['Учтите коммуникацию и обратную связь.', 'Держите прямые расходы на виду.', 'Используйте собственную цель как основу переговоров.'], tip: 'Если ставка с запасом слишком мала, увеличьте стоимость, сократите объём или ограничьте число правок.' }),
  },
  ja: {
    title: 'プロジェクト料金から時給への計算ツール', description: '修正、ミーティング、直接経費を含めて、固定プロジェクト料金を実質時給に換算します。', slug: 'project-fee-hourly-rate-calculator-japan', numberLocale: 'ja-JP',
    ui: { labelFee: '固定プロジェクト料金', labelPlannedHours: '実作業時間', labelRevisions: '修正ラウンド', labelRevisionHours: '修正1回あたりの時間', labelMeetings: 'ミーティング', labelMeetingHours: '1回あたりの時間', labelDirectCosts: 'プロジェクト直接経費', labelTargetRate: '目標時給', labelDelay: '追加時間シナリオ', labelEffectiveRate: '実質時給', labelAfterCosts: '直接経費控除後の料金', labelTotalHours: '現実的なプロジェクト時間', labelHiddenHours: '追加時間', labelBufferedRate: 'シナリオ後の時給', labelRecommendedFee: '目標達成に必要な料金', labelFeeGap: '交渉差額', labelPlanned: '予定作業', labelHidden: '追加作業', labelWorkloadLedger: '作業時間の内訳', labelHandsOn: '実作業', labelRevisionTime: '修正時間', labelMeetingTime: '会議時間', labelScenarioTotal: 'シナリオ余裕込み', labelBuffer: 'シナリオ', labelCurrency: '通貨', labelProjectMath: 'プロジェクト計算', titleInputs: '見えない作業を可視化', titleHiddenWork: '追加作業', titleResults: 'プロジェクトの時間内訳', statusBelow: '目標を下回る差額', statusAtOrAbove: '目標以上の差額', statusNoHours: '時給を見るにはプロジェクト時間を1時間以上入力してください。', noteBeforeTax: '税引き前。入力したデータだけを使い、ブラウザ内で計算します。', btnBuffer0: '余裕なし', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: '実質時給は何を示しますか？', answer: '固定料金から直接経費を引き、実作業、修正、ミーティングの時間を含めた場合に、1時間あたりいくら残るかを示します。' }, { question: 'どの時間を含めるべきですか？', answer: 'まず制作時間を入力し、現実的な修正回数とミーティングを追加してください。忘れがちな時間も見えるようになります。' }, { question: '余裕率はどのように働きますか？', answer: '選択した割合をプロジェクトの合計時間に加えます。追加作業を比較するシナリオであり、納期予測ではありません。' }, { question: '推奨料金はどう計算されますか？', answer: '直接経費に、合計時間と目標時給の積を加えます。このプロジェクトでの交渉用の下限です。' }],
    howTo: [{ name: '固定料金を入力', text: '税金や決済手数料を除く、クライアントの支払額を入力します。' }, { name: '追加作業を入力', text: '実作業、修正、ミーティングとそれぞれの時間を入力します。' }, { name: 'シナリオを選択', text: '10%、25%、50%を試して、追加作業による変化を確認します。' }, { name: '目標と比較', text: '希望時給を入力し、推奨料金を交渉の基準にします。' }],
    seo: commonSeo({ title: 'プロジェクトのすべての時間を数える', intro: '固定料金が魅力的なのは、見積もりがプロジェクト全体を含んでいる場合だけです。修正、連絡、直接経費によって、適正な見積もりが割に合わない仕事になることがあります。', formulaTitle: 'プロジェクト専用の計算式', formula: '実質時給 =（固定料金 - 直接経費）/（実作業時間 + 修正時間 + ミーティング時間）。', scenarioTitle: '交渉前にシナリオを試す', scenario: '余裕率は、すべてのプロジェクトがその割合だけ延びると主張するものではありません。作業が増えたときにも料金が妥当かを確認できます。', bullets: ['連絡とフィードバックの時間を含める。', '直接経費を見える状態にする。', '自分の目標時給を交渉の基準にする。'], tip: '余裕込みの時給が低い場合は、料金を上げる、範囲を減らす、修正回数を制限する、のいずれかを検討してください。' }),
  },
  ko: {
    title: '프로젝트 비용을 시간당 요금으로 계산기', description: '수정, 회의, 직접 비용을 반영해 고정 프로젝트 비용을 실제 시간당 요금으로 계산합니다.', slug: 'project-fee-hourly-rate-calculator-korea', numberLocale: 'ko-KR',
    ui: { labelFee: '고정 프로젝트 비용', labelPlannedHours: '실작업 시간', labelRevisions: '수정 라운드', labelRevisionHours: '수정 1회당 시간', labelMeetings: '회의', labelMeetingHours: '회의 1회당 시간', labelDirectCosts: '프로젝트 직접 비용', labelTargetRate: '목표 시간당 요금', labelDelay: '추가 시간 시나리오', labelEffectiveRate: '실제 시간당 요금', labelAfterCosts: '직접 비용 차감 후 비용', labelTotalHours: '현실적인 프로젝트 시간', labelHiddenHours: '추가 시간', labelBufferedRate: '시나리오 적용 요금', labelRecommendedFee: '목표 달성에 필요한 비용', labelFeeGap: '협상 차액', labelPlanned: '계획된 작업', labelHidden: '추가 작업', labelWorkloadLedger: '시간 내역', labelHandsOn: '실작업', labelRevisionTime: '수정 시간', labelMeetingTime: '회의 시간', labelScenarioTotal: '시나리오 여유 포함', labelBuffer: '시나리오', labelCurrency: '통화', labelProjectMath: '프로젝트 계산', titleInputs: '숨은 작업을 보이게 하기', titleHiddenWork: '추가 작업', titleResults: '시간으로 보는 프로젝트', statusBelow: '목표보다 낮은 차액', statusAtOrAbove: '목표 이상인 차액', statusNoHours: '요금을 보려면 프로젝트 시간을 한 시간 이상 입력하세요.', noteBeforeTax: '세금 전 금액입니다. 입력한 데이터만 사용하며 브라우저에서 계산합니다.', btnBuffer0: '여유 없음', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: '실제 시간당 요금은 무엇을 보여주나요?', answer: '직접 비용을 빼고 실작업, 수정, 회의 시간을 포함했을 때 고정 비용에서 시간당 얼마가 남는지 보여줍니다.' }, { question: '어떤 시간을 포함해야 하나요?', answer: '먼저 제작 시간을 입력하고 현실적인 수정과 회의를 추가해 자주 빠지는 시간을 드러내세요.' }, { question: '여유 시나리오는 어떻게 작동하나요?', answer: '선택한 비율을 프로젝트 전체 시간에 더합니다. 추가 작업을 비교하는 시나리오이며 일정 예측은 아닙니다.' }, { question: '추천 비용은 어떻게 계산하나요?', answer: '직접 비용에 전체 시간과 목표 요금의 곱을 더합니다. 이 프로젝트를 위한 개인 협상 기준입니다.' }],
    howTo: [{ name: '고정 비용 입력', text: '세금과 결제 수수료 전 고객이 지불할 금액을 입력합니다.' }, { name: '추가 작업 입력', text: '실작업, 수정, 회의와 각각의 시간을 입력합니다.' }, { name: '시나리오 선택', text: '10%, 25%, 50%를 시험해 추가 작업의 영향을 확인합니다.' }, { name: '목표와 비교', text: '원하는 요금을 입력하고 추천 비용을 협상 기준으로 사용합니다.' }],
    seo: commonSeo({ title: '프로젝트의 모든 시간을 계산하세요', intro: '고정 비용은 견적에 프로젝트 전체가 포함될 때만 매력적입니다. 수정, 연락, 직접 비용은 괜찮은 제안을 낮은 보상의 약속으로 바꿀 수 있습니다.', formulaTitle: '프로젝트별 공식', formula: '실제 요금 = (고정 비용 - 직접 비용) / (실작업 시간 + 수정 시간 + 회의 시간).', scenarioTitle: '협상 전에 시나리오 확인', scenario: '여유율은 모든 프로젝트가 정확히 그 비율만큼 길어진다는 뜻이 아닙니다. 작업이 늘어도 비용이 타당한지 확인하는 방법입니다.', bullets: ['소통과 피드백 시간을 포함하세요.', '직접 비용을 항상 보이게 하세요.', '자신의 목표를 협상 기준으로 삼으세요.'], tip: '여유를 적용한 요금이 낮다면 비용을 올리거나 범위를 줄이거나 포함되는 수정 횟수를 제한하세요.' }),
  },
  zh: {
    title: '项目费用转时薪计算器', description: '在加入修改、会议和直接成本后，将固定项目费用换算为实际时薪。', slug: 'project-fee-hourly-rate-calculator-china', numberLocale: 'zh-CN',
    ui: { labelFee: '固定项目费用', labelPlannedHours: '实际工作小时', labelRevisions: '修改轮次', labelRevisionHours: '每轮修改小时', labelMeetings: '会议', labelMeetingHours: '每次会议小时', labelDirectCosts: '项目直接成本', labelTargetRate: '你的目标时薪', labelDelay: '额外工时场景', labelEffectiveRate: '实际时薪', labelAfterCosts: '扣除直接成本后的费用', labelTotalHours: '项目实际总工时', labelHiddenHours: '额外工时', labelBufferedRate: '场景时薪', labelRecommendedFee: '达到目标所需费用', labelFeeGap: '谈判差额', labelPlanned: '计划工作', labelHidden: '额外工作', labelWorkloadLedger: '工时明细', labelHandsOn: '实际工作', labelRevisionTime: '修改时间', labelMeetingTime: '会议时间', labelScenarioTotal: '包含场景余量', labelBuffer: '场景', labelCurrency: '货币', labelProjectMath: '项目计算', titleInputs: '让隐藏工作变得可见', titleHiddenWork: '额外工作', titleResults: '你的项目工时', statusBelow: '低于目标', statusAtOrAbove: '达到或超过目标', statusNoHours: '至少添加一小时项目工时后才能看到时薪。', noteBeforeTax: '税前金额。只使用你输入的数据，并在浏览器中运行。', btnBuffer0: '无余量', btnBuffer10: '+10%', btnBuffer25: '+25%', btnBuffer50: '+50%' },
    faq: [{ question: '实际时薪显示什么？', answer: '它显示扣除直接成本并计入实际工作、修改和会议后，固定费用平均到每小时还剩多少。' }, { question: '应该包含哪些工时？', answer: '先填写制作工时，再加入合理的修改和会议时间，让容易遗漏的工作也显示出来。' }, { question: '余量场景如何工作？', answer: '所选百分比会加到项目总工时中。这是比较额外工作的场景，不是交付日期预测。' }, { question: '推荐费用如何计算？', answer: '将直接成本加上总工时乘以目标时薪的金额，作为本项目的个人谈判底线。' }],
    howTo: [{ name: '输入固定费用', text: '填写客户在税费和支付手续费前需要支付的金额。' }, { name: '加入额外工作', text: '输入实际工作、修改、会议及其所需时间。' }, { name: '选择场景', text: '尝试 10%、25% 或 50%，查看额外工作如何影响时薪。' }, { name: '与目标比较', text: '输入期望时薪，并在报价或谈判时参考推荐费用。' }],
    seo: commonSeo({ title: '计算项目中的每一个小时', intro: '只有估算包含整个项目时，固定费用才真正有吸引力。修改、沟通和直接成本可能让看似合理的报价变成低回报的承诺。', formulaTitle: '项目专属公式', formula: '实际时薪 =（固定费用 - 直接成本）/（实际工作小时 + 修改小时 + 会议小时）。', scenarioTitle: '谈判前先测试场景', scenario: '余量并不是说每个项目都会准确增加这个百分比，而是帮助你判断工作增加后价格是否仍然合理。', bullets: ['把沟通和反馈时间算进去。', '让直接成本保持可见。', '用自己的目标时薪作为谈判基础。'], tip: '如果加入余量后的时薪太低，可以提高费用、缩小范围，或限制包含的修改次数。' }),
  },
};

export function getLocalizedProjectFeeContent(locale: string) {
  const copy = data[locale];
  if (!copy) throw new Error(`Missing project fee locale: ${locale}`);
  return createProjectFeeContent({
    locale,
    slug: copy.slug,
    title: copy.title,
    description: copy.description,
    ui: { ...copy.ui, numberLocale: copy.numberLocale },
    faq: copy.faq,
    howTo: copy.howTo,
    seo: copy.seo,
    bibliography,
  });
}
