export { autonomosCalculator } from './tool/autonomosCalculator/entry';
export type { AutonomosCalculatorLocaleContent } from './tool/autonomosCalculator/entry';
export { earlyRetirementSimulator } from './tool/earlyRetirementSimulator/entry';
export type { EarlyRetirementSimulatorLocaleContent } from './tool/earlyRetirementSimulator/entry';
export { invoiceGenerator } from './tool/invoiceGenerator/entry';
export type { InvoiceGeneratorLocaleContent } from './tool/invoiceGenerator/entry';
export { irpfCalculator } from './tool/irpfCalculator/entry';
export type { IrpfCalculatorLocaleContent } from './tool/irpfCalculator/entry';
export { meetingCostCalculator } from './tool/meetingCostCalculator/entry';
export type { MeetingCostCalculatorLocaleContent } from './tool/meetingCostCalculator/entry';
export { nieNifVerifier } from './tool/nieNifVerifier/entry';
export type { NieNifVerifierLocaleContent } from './tool/nieNifVerifier/entry';
export { resignationLetterGenerator } from './tool/resignationLetterGenerator/entry';
export type { ResignationLetterGeneratorLocaleContent } from './tool/resignationLetterGenerator/entry';
export { reverseVatCalculator } from './tool/reverseVatCalculator/entry';
export type { ReverseVatCalculatorLocaleContent } from './tool/reverseVatCalculator/entry';
export { salaryCalculator } from './tool/salaryCalculator/entry';
export type { SalaryCalculatorLocaleContent } from './tool/salaryCalculator/entry';
export { settlementCalculator } from './tool/settlementCalculator/entry';
export type { SettlementCalculatorLocaleContent } from './tool/settlementCalculator/entry';
export { workCategory } from './category';
import { autonomosCalculator } from './tool/autonomosCalculator/entry';
import { earlyRetirementSimulator } from './tool/earlyRetirementSimulator/entry';
import { invoiceGenerator } from './tool/invoiceGenerator/entry';
import { irpfCalculator } from './tool/irpfCalculator/entry';
import { meetingCostCalculator } from './tool/meetingCostCalculator/entry';
import { nieNifVerifier } from './tool/nieNifVerifier/entry';
import { resignationLetterGenerator } from './tool/resignationLetterGenerator/entry';
import { reverseVatCalculator } from './tool/reverseVatCalculator/entry';
import { salaryCalculator } from './tool/salaryCalculator/entry';
import { settlementCalculator } from './tool/settlementCalculator/entry';
export const ALL_ENTRIES = [autonomosCalculator, earlyRetirementSimulator, invoiceGenerator, irpfCalculator, meetingCostCalculator, nieNifVerifier, resignationLetterGenerator, reverseVatCalculator, salaryCalculator, settlementCalculator];
